/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_annotion_ruiyi_forkprocesstest_JniHelper */

#ifndef _Included_com_annotion_ruiyi_forkprocesstest_JniHelper
#define _Included_com_annotion_ruiyi_forkprocesstest_JniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_annotion_ruiyi_forkprocesstest_JniHelper
 * Method:    forkProcess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_annotion_ruiyi_forkprocesstest_JniHelper_forkProcess
  (JNIEnv *, jclass);

/*
 * Class:     com_annotion_ruiyi_forkprocesstest_JniHelper
 * Method:    testJar
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_annotion_ruiyi_forkprocesstest_JniHelper_testJar
  (JNIEnv *, jclass ,jstring , jstring , jstring , jstring );

#ifdef __cplusplus
}
#endif
#endif
